#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
@file lv_api.py
@brief Render LVGL SNI API wrappers from the accepted resolved API surface
"""

from __future__ import annotations

import fnmatch
import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple

from ..core.ir import ApiClassIR, ApiConstantIR, ApiMacroIR, ApiRecord, ApiStatus, ApiUse, ResolvedApiSurface
from ..core.lvgl_model import normalize_c_type_node


HEADER_TEXT = """/**
 * @file sni_api_lv.c
 * @brief LVGL API export
 **************************************************************************
 * This file is auto-generated by generate_sni.py. Do not edit manually.
 **************************************************************************
 */

#include "sni_api_lv.h"

/* Includes ---------------------------------------------------*/
#include <stdio.h>
#include <stdlib.h>
#include "lvgl.h"
#include "src/core/lv_obj_private.h"
#include "sni_type_bridge.h"
#include "sni_types.h"
#include "sni_api_export.h"
#include "sni_callback_runtime.h"
#include "sni_api_lv_special.h"
#include "eos_log.h"
#include "eos_mem.h"
/* Macros and Definitions -------------------------------------*/
#define LV_API_NAME "lv"
/* Variables --------------------------------------------------*/
static jerry_value_t lv_api_obj;
/* Function Implementations -----------------------------------*/
"""


@dataclass
class TypeBridge:
    c_type: str
    js_check: str
    js2c_mode: str
    js2c_expr: Optional[str]
    sni_type: Optional[str]
    c2js_mode: str
    c2js_expr: Optional[str]


@dataclass
class FuncArg:
    name: str
    c_type: str
    bridge: TypeBridge
    docstring: str = ""
    js_type: str = "unknown"
    lifecycle_class: str = ""
    argument_mode: str = "value"
    allow_null: bool = False
    copy_back: bool = False
    pointee_type: Optional[str] = None


@dataclass
class ApiFunction:
    name: str
    return_type: str
    return_bridge: TypeBridge
    args: List[FuncArg]
    docstring: str = ""
    return_docstring: str = ""
    return_js_type: str = "unknown"
    lifecycle_class: str = ""
    native_call_name: Optional[str] = None
    output_string: Optional[Tuple[str, str, str]] = None
    result_owner: Optional[str] = None
    cleanup_parameters: List[str] = field(default_factory=list)


@dataclass
class ArgRenderResult:
    call_expr: str
    post_lines: List[str]


@dataclass
class FilterStats:
    total: int = 0
    blacklisted: int = 0
    whitelist_miss: int = 0
    included: int = 0
    skipped_by_user: int = 0


def normalize_c_type(type_info: Optional[Dict[str, Any]]) -> str:
    return normalize_c_type_node(type_info)


def normalize_type_key(c_type: str) -> str:
    text = c_type.replace("const", " ")
    text = re.sub(r"\s+", " ", text).strip()
    text = text.replace(" *", "*").replace("* ", "*")
    return text


def is_value_pointer_arg(arg: FuncArg) -> bool:
    return arg.argument_mode in {"value_pointer", "value_pointer_output"}


def parse_api_filters(api_table: Dict[str, Any]) -> Dict[str, Dict[str, List[str]]]:
    result = {
        "function": {"whitelist": [], "blacklist": []},
        "constant": {"whitelist": [], "blacklist": []},
    }

    scan = api_table.get("scan", {}) if isinstance(api_table.get("scan", {}), dict) else {}
    for group in ("function", "constant"):
        group_obj = scan.get(group, {})
        if not isinstance(group_obj, dict):
            raise SystemExit(f"[Error] api-table field scan.{group} must be an object")
        for key in ("whitelist", "blacklist"):
            value = group_obj.get(key, [])
            if not isinstance(value, list):
                raise SystemExit(f"[Error] api-table field scan.{group}.{key} must be an array")
            result[group][key] = [str(item).strip() for item in value if str(item).strip()]
    return result


def parse_function_overrides(api_table: Dict[str, Any]) -> Dict[str, Dict[str, Any]]:
    overrides = api_table.get("function_overrides", {})
    if not isinstance(overrides, dict):
        raise SystemExit("[Error] api-table field function_overrides must be an object")

    result: Dict[str, Dict[str, Any]] = {}
    for name, value in overrides.items():
        if not isinstance(value, dict):
            raise SystemExit(f"[Error] function_overrides.{name} must be an object")
        result[str(name)] = value
    return result


@dataclass
class ApiClass:
    name: str
    c_type: str
    constructor: Optional[str]
    base: Optional[str]
    methods: List["ApiMethodSelector"]
    static_methods: List["ApiMethodSelector"]
    constants: List[str]


@dataclass
class ApiProperty:
    name: str
    getter: Optional[str]
    setter: Optional[str]


@dataclass
class ApiMethodArgMatcher:
    index: int
    name_pattern: Optional[str]
    type_pattern: Optional[str]


@dataclass
class ApiMethodSelector:
    name_pattern: str
    arg_matchers: List[ApiMethodArgMatcher]
    raw_text: str
    exclusions: List[str]


def parse_method_selector(
    item: Any,
    class_name: str,
    field_name: str,
    item_index: int,
) -> ApiMethodSelector:
    context = f"classes.{class_name}.{field_name}[{item_index}]"

    if isinstance(item, str):
        name_pattern = item.strip()
        if not name_pattern:
            raise SystemExit(f"[Error] {context} cannot be an empty string")
        return ApiMethodSelector(name_pattern=name_pattern, arg_matchers=[], raw_text=name_pattern, exclusions=[])

    if not isinstance(item, dict):
        raise SystemExit(f"[Error] {context} must be a string or object")

    name_pattern = str(item.get("name", item.get("match", item.get("pattern", "*")))).strip()
    if not name_pattern:
        name_pattern = "*"

    arg_rules_raw: Any
    if "arg_match" in item:
        arg_rules_raw = item.get("arg_match")
    elif "args" in item:
        arg_rules_raw = item.get("args")
    elif "arg" in item:
        arg_rules_raw = item.get("arg")
    else:
        arg_rules_raw = []

    if isinstance(arg_rules_raw, dict):
        arg_rules = [arg_rules_raw]
    elif isinstance(arg_rules_raw, list):
        arg_rules = arg_rules_raw
    else:
        raise SystemExit(f"[Error] {context}.arg_match/args/arg must be an object or array")

    parsed_arg_rules: List[ApiMethodArgMatcher] = []
    for ridx, rule in enumerate(arg_rules):
        rule_ctx = f"{context}.arg_match[{ridx}]"
        if not isinstance(rule, dict):
            raise SystemExit(f"[Error] {rule_ctx} must be an object")

        raw_index = None
        if "index" in rule:
            raw_index = rule.get("index")
            try:
                arg_index = int(raw_index)
            except (TypeError, ValueError):
                raise SystemExit(f"[Error] {rule_ctx}.index must be an integer")
            if arg_index < 0:
                raise SystemExit(f"[Error] {rule_ctx}.index must be >= 0")
        else:
            nth_value = rule.get("nth", rule.get("n", rule.get("position")))
            if nth_value is None:
                raise SystemExit(f"[Error] {rule_ctx} must provide index(0-based) or nth/n/position(1-based)")
            try:
                nth = int(nth_value)
            except (TypeError, ValueError):
                raise SystemExit(f"[Error] {rule_ctx}.nth must be an integer")
            if nth <= 0:
                raise SystemExit(f"[Error] {rule_ctx}.nth must be >= 1")
            arg_index = nth - 1

        name_pattern_rule = None
        if "name" in rule and rule.get("name") is not None:
            val = str(rule.get("name")).strip()
            if val:
                name_pattern_rule = val

        type_pattern_rule = None
        if "type" in rule and rule.get("type") is not None:
            val = str(rule.get("type")).strip()
            if val:
                type_pattern_rule = normalize_type_key(val)

        if name_pattern_rule is None and type_pattern_rule is None:
            raise SystemExit(f"[Error] {rule_ctx} must provide at least name or type")

        parsed_arg_rules.append(
            ApiMethodArgMatcher(
                index=arg_index,
                name_pattern=name_pattern_rule,
                type_pattern=type_pattern_rule,
            )
        )

    excluded = item.get("exclude", [])
    if not isinstance(excluded, list) or not all(isinstance(name, str) and name.strip() for name in excluded):
        raise SystemExit(f"[Error] {context}.exclude must be a string array")
    raw_text = json.dumps(item, ensure_ascii=False, sort_keys=True)
    return ApiMethodSelector(name_pattern=name_pattern, arg_matchers=parsed_arg_rules, raw_text=raw_text, exclusions=list(excluded))


def parse_method_selectors(entries: Any, class_name: str, field_name: str) -> List[ApiMethodSelector]:
    if isinstance(entries, (str, dict)):
        entries = [entries]
    elif not isinstance(entries, list):
        raise SystemExit(
            f"[Error] classes.{class_name}.{field_name} must be an array, or a single string/object"
        )

    selectors: List[ApiMethodSelector] = []
    for idx, item in enumerate(entries):
        selectors.append(parse_method_selector(item, class_name, field_name, idx))
    return selectors


def parse_api_classes(api_table: Dict[str, Any]) -> Dict[str, ApiClass]:
    classes_raw = api_table.get("classes")
    if not isinstance(classes_raw, dict) or not classes_raw:
        raise SystemExit("[Error] api-table missing classes definition")

    classes: Dict[str, ApiClass] = {}
    for class_name, cfg in classes_raw.items():
        if not isinstance(cfg, dict):
            raise SystemExit(f"[Error] classes.{class_name} must be an object")

        c_type = str(cfg.get("c_type", "")).strip()
        ctor_val = cfg.get("constructor", None)
        constructor = None if ctor_val is None else str(ctor_val).strip()
        base_val = cfg.get("base")
        base = None if base_val is None else str(base_val).strip()
        methods = cfg.get("methods", [])
        static_methods = cfg.get("static_methods", [])
        constants = cfg.get("constants", [])

        if not c_type:
            raise SystemExit(f"[Error] classes.{class_name}.c_type cannot be empty")
        if constructor == "":
            constructor = None
        if not isinstance(constants, list):
            raise SystemExit(f"[Error] classes.{class_name}.constants must be an array")

        methods_norm = parse_method_selectors(methods, class_name, "methods")
        static_methods_norm = parse_method_selectors(static_methods, class_name, "static_methods")
        constants_norm = [str(item).strip() for item in constants if str(item).strip()]

        if constructor is None:
            if methods_norm:
                raise SystemExit(f"[Error] classes.{class_name} is a static class(constructor=null), methods must be empty")
            if not static_methods_norm:
                raise SystemExit(f"[Error] classes.{class_name} is a static class(constructor=null), static_methods cannot be empty")

        classes[class_name] = ApiClass(
            name=class_name,
            c_type=c_type,
            constructor=constructor,
            base=base if base else None,
            methods=methods_norm,
            static_methods=static_methods_norm,
            constants=constants_norm,
        )

    for class_name, cls in classes.items():
        if cls.base and cls.base not in classes:
            raise SystemExit(f"[Error] classes.{class_name}.base references a non-existent class: {cls.base}")

    temp_mark: Set[str] = set()
    perm_mark: Set[str] = set()

    def visit(name: str) -> None:
        if name in perm_mark:
            return
        if name in temp_mark:
            raise SystemExit(f"[Error] classes has cyclic inheritance: {name}")

        temp_mark.add(name)
        parent = classes[name].base
        if parent:
            visit(parent)
        temp_mark.remove(name)
        perm_mark.add(name)

    for name in classes.keys():
        visit(name)

    return classes


def is_matched(name: str, patterns: List[str]) -> bool:
    for pattern in patterns:
        if fnmatch.fnmatchcase(name, pattern):
            return True
    return False


def include_by_filter(
    name: str,
    whitelist: List[str],
    blacklist: List[str],
    stats: Optional[FilterStats] = None,
) -> bool:
    if stats is not None:
        stats.total += 1
    if blacklist and is_matched(name, blacklist):
        if stats is not None:
            stats.blacklisted += 1
        return False
    if whitelist and not is_matched(name, whitelist):
        if stats is not None:
            stats.whitelist_miss += 1
        return False
    if stats is not None:
        stats.included += 1
    return True


def load_lvgl_version(version_header_path: Path) -> Tuple[int, int, int]:
    """Read the LVGL version directly from lv_version.h."""
    try:
        version_text = version_header_path.read_text(encoding="utf-8")
    except OSError as err:
        raise SystemExit(f"[Error] unable to read LVGL version header: {version_header_path}") from err

    version: Dict[str, int] = {}
    for match in re.finditer(
        r"^\s*#define\s+LVGL_VERSION_(MAJOR|MINOR|PATCH)\s+(\d+)\s*$",
        version_text,
        re.MULTILINE,
    ):
        version[match.group(1).lower()] = int(match.group(2))

    missing = [component for component in ("major", "minor", "patch") if component not in version]
    if missing:
        missing_text = ", ".join(f"LVGL_VERSION_{component.upper()}" for component in missing)
        raise SystemExit(f"[Error] {missing_text} missing from {version_header_path}")

    return version["major"], version["minor"], version["patch"]


def render_lvgl_compatibility_guard(
    lvgl_version: Tuple[int, int, int], event_assertions: List[Tuple[str, str]]
) -> str:
    """Render compile-time guards for the generated LVGL descriptor."""
    major, minor, patch = lvgl_version
    lines = [
        "/* Compile-time compatibility guard generated from lv_version.h. */",
        f"#define SNI_LVGL_API_VERSION_MAJOR {major}",
        f"#define SNI_LVGL_API_VERSION_MINOR {minor}",
        f"#define SNI_LVGL_API_VERSION_PATCH {patch}",
        "",
        "#if LVGL_VERSION_MAJOR != SNI_LVGL_API_VERSION_MAJOR || \\",
        "    LVGL_VERSION_MINOR != SNI_LVGL_API_VERSION_MINOR || \\",
        "    LVGL_VERSION_PATCH != SNI_LVGL_API_VERSION_PATCH",
        '#error "sni_api_lv.c was generated for a different LVGL version; regenerate lvgl.json and sni_api_lv.c"',
        "#endif",
        "",
        "/* The event enum is ABI-sensitive even when the semantic version is unchanged. */",
        "#define SNI_LVGL_API_STATIC_ASSERT(expr, name) typedef char name[(expr) ? 1 : -1]",
    ]

    for name, value in event_assertions:
        assert_name = f"sni_lvgl_api_assert_{name.lower()}"
        lines.append(f"SNI_LVGL_API_STATIC_ASSERT({name} == {value}, {assert_name});")

    lines.extend(
        [
            "#undef SNI_LVGL_API_STATIC_ASSERT",
            "",
        ]
    )
    return "\n".join(lines)


def topo_sort_classes(classes: Dict[str, ApiClass]) -> List[ApiClass]:
    ordered: List[ApiClass] = []
    temp_mark: Set[str] = set()
    perm_mark: Set[str] = set()

    def visit(name: str) -> None:
        if name in perm_mark:
            return
        if name in temp_mark:
            raise SystemExit(f"[Error] classes has cyclic inheritance: {name}")
        temp_mark.add(name)
        base = classes[name].base
        if base:
            visit(base)
        temp_mark.remove(name)
        perm_mark.add(name)
        ordered.append(classes[name])

    for name in classes.keys():
        visit(name)

    return ordered


def build_function_index(lvgl_data: Dict[str, Any]) -> Dict[str, Dict[str, Any]]:
    result: Dict[str, Dict[str, Any]] = {}
    for item in lvgl_data.get("functions", []):
        name = str(item.get("name", "")).strip()
        if not name:
            continue
        result[name] = item
    return result


def require_function(function_index: Dict[str, Dict[str, Any]], name: str, context: str) -> Dict[str, Any]:
    if name not in function_index:
        raise SystemExit(f"[Error] Cannot find function {name} ({context})")
    return function_index[name]


def require_class_function(
    function_index: Dict[str, Dict[str, Any]],
    class_name: str,
    name: str,
    context: str,
) -> Dict[str, Any]:
    normalized = str(name).strip()
    candidates: List[str] = [normalized]
    if normalized and not normalized.startswith("lv_"):
        candidates.insert(0, f"lv_{class_name}_{normalized}")
        candidates.append(f"lv_{normalized}")

    seen: Set[str] = set()
    dedup_candidates: List[str] = []
    for candidate in candidates:
        if candidate and candidate not in seen:
            dedup_candidates.append(candidate)
            seen.add(candidate)

    for candidate in dedup_candidates:
        if candidate in function_index:
            return function_index[candidate]

    raise SystemExit(
        f"[Error] Cannot find function {name} ({context}), tried: {', '.join(dedup_candidates)}"
    )


def build_selector_name_patterns(class_name: str, name_pattern: str) -> List[str]:
    pattern = str(name_pattern).strip() or "*"
    if pattern.startswith("lv_"):
        return [pattern]

    candidates = [f"lv_{class_name}_{pattern}", f"lv_{pattern}", pattern]
    result: List[str] = []
    seen: Set[str] = set()
    for item in candidates:
        if item not in seen:
            seen.add(item)
            result.append(item)
    return result


def has_wildcard_pattern(text: str) -> bool:
    return any(ch in text for ch in "*?[")


def function_name_matches_selector(class_name: str, selector: ApiMethodSelector, func_name: str) -> bool:
    if func_name in selector.exclusions:
        return False
    patterns = build_selector_name_patterns(class_name, selector.name_pattern)
    for pattern in patterns:
        if has_wildcard_pattern(pattern):
            if fnmatch.fnmatchcase(func_name, pattern):
                return True
        else:
            if func_name == pattern:
                return True
    return False


def function_args_match_selector(selector: ApiMethodSelector, func_item: Dict[str, Any]) -> bool:
    if not selector.arg_matchers:
        return True

    args = normalize_args(func_item.get("args", []))
    for matcher in selector.arg_matchers:
        if matcher.index >= len(args):
            return False

        arg = args[matcher.index]
        arg_name = str(arg.get("name") or "").strip()
        arg_type = normalize_type_key(normalize_c_type(arg.get("type")))

        if matcher.name_pattern is not None and not fnmatch.fnmatchcase(arg_name, matcher.name_pattern):
            return False

        if matcher.type_pattern is not None and not fnmatch.fnmatchcase(arg_type, matcher.type_pattern):
            return False

    return True


def resolve_class_selector_items(
    function_index: Dict[str, Dict[str, Any]],
    class_name: str,
    selector: ApiMethodSelector,
    context: str,
) -> List[Dict[str, Any]]:
    matches: List[Dict[str, Any]] = []
    for func_name, item in function_index.items():
        if not function_name_matches_selector(class_name, selector, func_name):
            continue
        if not function_args_match_selector(selector, item):
            continue
        matches.append(item)

    if not matches:
        patterns = build_selector_name_patterns(class_name, selector.name_pattern)
        raise SystemExit(
            f"[Error] Cannot find function match {context}: {selector.raw_text}, tried name patterns: {', '.join(patterns)}"
        )

    return matches


def sanitize_ident(text: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_]", "_", text)


def snake_to_camel(text: str) -> str:
    parts = text.split("_")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def discover_class_properties(
    cls: ApiClass,
    function_index: Dict[str, Dict[str, Any]],
    filters: Dict[str, Dict[str, List[str]]],
) -> List[ApiProperty]:
    if cls.constructor is None:
        return []

    func_filter = filters.get("function", {})
    blacklist = func_filter.get("blacklist", [])

    get_prefix = f"lv_{cls.name}_get_"
    set_prefix = f"lv_{cls.name}_set_"
    props: Dict[str, ApiProperty] = {}

    for func_name in sorted(function_index.keys()):
        if blacklist and is_matched(func_name, blacklist):
            continue

        if func_name.startswith(get_prefix):
            prop_name = func_name[len(get_prefix):]
            if prop_name:
                existing = props.get(prop_name)
                if existing:
                    existing.getter = func_name
                else:
                    props[prop_name] = ApiProperty(name=prop_name, getter=func_name, setter=None)
            continue

        if func_name.startswith(set_prefix):
            prop_name = func_name[len(set_prefix):]
            if prop_name:
                existing = props.get(prop_name)
                if existing:
                    existing.setter = func_name
                else:
                    props[prop_name] = ApiProperty(name=prop_name, getter=None, setter=func_name)

    return [props[name] for name in sorted(props.keys())]


def fmt_var_decl(c_type: str, var_name: str) -> str:
    """Format a variable declaration with right-aligned pointer spacing.

    Produces 'lv_obj_t *var' for pointer types and 'int32_t var' otherwise.
    """
    c_type = c_type.strip()
    return f"{c_type}{var_name}" if c_type.endswith("*") else f"{c_type} {var_name}"


def render_arg_conversion(
    lines: List[str],
    arg_expr: str,
    arg: FuncArg,
    c_var_name: str,
    allow_null: bool = False,
    output_only_value_arg: bool = False,
) -> ArgRenderResult:
    is_nullable_ptr = (
        allow_null
        and arg.allow_null
        and arg.bridge.js2c_mode == "bridge"
        and arg.bridge.sni_type is not None
    )
    if is_nullable_ptr:
        post_lines: List[str] = []
        lines.append(f"    {fmt_var_decl(arg.c_type, c_var_name)};")
        lines.append(f"    if (jerry_value_is_null({arg_expr}))")
        lines.append("    {")
        lines.append(f"        {c_var_name} = NULL;")
        lines.append("    }")
        if not arg.bridge.js_check:
            raise RuntimeError(f"Resolved nullable argument {arg.name} has no JavaScript type check")
        lines.append(f"    else if ({arg.bridge.js_check}({arg_expr}))")
        lines.append("    {")
        lines.append(f"        if (!sni_tb_js2c({arg_expr}, {arg.bridge.sni_type}, &{c_var_name}))")
        lines.append("        {")
        lines.append('            return sni_api_throw_error("Failed to convert argument");')
        lines.append("        }")
        lines.append("    }")
        lines.append("    else")
        lines.append("    {")
        lines.append('        return sni_api_throw_error("Invalid argument type");')
        lines.append("    }")
        return ArgRenderResult(call_expr=c_var_name, post_lines=post_lines)

    if is_value_pointer_arg(arg):
        if not output_only_value_arg:
            check = arg.bridge.js_check
            if check:
                lines.append(f"    if (!{check}({arg_expr}))")
                lines.append("    {")
                lines.append('        return sni_api_throw_error("Invalid argument type");')
                lines.append("    }")

        value_var = f"{c_var_name}_value"
        if not arg.pointee_type:
            raise RuntimeError(f"Resolved value-pointer argument {arg.name} has no pointee C type")
        value_c_type = arg.pointee_type
        if output_only_value_arg:
            lines.append(f"    {fmt_var_decl(value_c_type, value_var)} = {{0}};")
        else:
            lines.append(f"    {fmt_var_decl(value_c_type, value_var)};")
            lines.append(f"    if (!sni_tb_js2c({arg_expr}, {arg.bridge.sni_type}, &{value_var}))")
            lines.append("    {")
            lines.append('        return sni_api_throw_error("Failed to convert argument");')
            lines.append("    }")

        post_lines: List[str] = []
        if arg.copy_back:
            post_lines.append(f"    if (!sni_tb_c2js_set_object(&{value_var}, {arg.bridge.sni_type}, {arg_expr}))")
            post_lines.append("    {")
            post_lines.append('        return sni_api_throw_error("Failed to convert return argument");')
            post_lines.append("    }")

        return ArgRenderResult(call_expr=f"&{value_var}", post_lines=post_lines)

    check = arg.bridge.js_check
    if check:
        lines.append(f"    if (!{check}({arg_expr}))")
        lines.append("    {")
        lines.append('        return sni_api_throw_error("Invalid argument type");')
        lines.append("    }")

    lines.append(f"    {fmt_var_decl(arg.c_type, c_var_name)};")

    if arg.bridge.js2c_mode == "macro" and arg.bridge.js2c_expr:
        lines.append(f"    {c_var_name} = {arg.bridge.js2c_expr}({arg_expr});")
    elif arg.bridge.js2c_mode == "string_fn" and arg.bridge.js2c_expr:
        lines.append(f"    {c_var_name} = {arg.bridge.js2c_expr}({arg_expr});")
        lines.append(f"    if (!{c_var_name})")
        lines.append("    {")
        lines.append('        return sni_api_throw_error("Out of memory");')
        lines.append("    }")
    elif arg.bridge.js2c_mode == "bridge" and arg.bridge.sni_type:
        lines.append(f"    if (!sni_tb_js2c({arg_expr}, {arg.bridge.sni_type}, &{c_var_name}))")
        lines.append("    {")
        lines.append('        return sni_api_throw_error("Failed to convert argument");')
        lines.append("    }")
    else:
        raise RuntimeError(
            f"Resolved argument conversion is incomplete for {arg.name}: "
            f"mode={arg.bridge.js2c_mode}, sni_type={arg.bridge.sni_type}"
        )

    post_lines = []
    if arg.bridge.js2c_mode == "string_fn":
        post_lines.append(f"    eos_free((void *){c_var_name});")
    return ArgRenderResult(call_expr=c_var_name, post_lines=post_lines)


def render_return_conversion(lines: List[str], func: ApiFunction, result_var: str) -> None:
    if func.return_bridge.c2js_mode == "void":
        lines.append("    return jerry_undefined();")
        return

    if func.return_bridge.c2js_mode == "macro" and func.return_bridge.c2js_expr:
        lines.append(f"    return {func.return_bridge.c2js_expr}({result_var});")
        return

    if func.return_bridge.c2js_mode == "string" and func.return_bridge.c2js_expr:
        lines.append(f"    return {func.return_bridge.c2js_expr}({result_var});")
        return

    if func.return_bridge.c2js_mode == "bridge" and func.return_bridge.sni_type:
        lines.append(f"    return sni_tb_c2js(&{result_var}, {func.return_bridge.sni_type});")
        return

    raise RuntimeError(
        f"Resolved return conversion is incomplete for {func.name}: "
        f"mode={func.return_bridge.c2js_mode}, sni_type={func.return_bridge.sni_type}"
    )


def _doc_lines(text: str) -> List[str]:
    return [line.strip() for line in text.replace("*/", "* /").splitlines() if line.strip()]


def _doc_brief_and_details(text: str) -> Tuple[str, List[str]]:
    paragraphs = [part.strip() for part in re.split(r"\n\s*\n", text.strip()) if part.strip()]
    if not paragraphs:
        return "", []
    return paragraphs[0].replace("\n", " "), paragraphs[1:]


def render_function_docstring(lines: List[str], func: ApiFunction, skip_this: bool = False) -> None:
    brief, details = _doc_brief_and_details(func.docstring)
    if not brief:
        brief = f"JavaScript binding for {func.name}."

    lines.append("/**")
    lines.append(f" * @brief {brief}")

    if details:
        lines.append(" *")
        lines.append(" * @details")
        for detail in details:
            for detail_line in _doc_lines(detail):
                lines.append(f" * {detail_line}")

    args = func.args[1:] if skip_this and func.args else func.args
    for arg in args:
        description = arg.docstring or "JavaScript argument."
        lines.append(" *")
        lines.append(f" * @param {arg.name} ({arg.js_type}) {description}")

    if func.return_js_type != "undefined":
        description = func.return_docstring or "JavaScript return value."
        lines.append(" *")
        lines.append(f" * @return ({func.return_js_type}) {description}")

    lines.append(" */")


def render_constructor_wrapper(cls: ApiClass, ctor_func: ApiFunction) -> str:
    wrapper_name = f"sni_api_ctor_{sanitize_ident(cls.name)}"
    lines: List[str] = []
    render_function_docstring(lines, ctor_func)

    func_prefix = f"jerry_value_t {wrapper_name}("
    func_indent = " " * len(func_prefix)
    lines.append(f"{func_prefix}const jerry_call_info_t *call_info_p,")
    lines.append(f"{func_indent}const jerry_value_t args_p[],")
    lines.append(f"{func_indent}const jerry_length_t args_count)")
    lines.append("{")
    lines.append("    if (jerry_value_is_undefined(call_info_p->new_target))")
    lines.append("    {")
    lines.append('        return sni_api_throw_error("Constructor must be called with new");')
    lines.append("    }")
    lines.append("")
    lines.append(f"    if (args_count != {len(ctor_func.args)})")
    lines.append("    {")
    lines.append('        return sni_api_throw_error("Invalid argument count");')
    lines.append("    }")
    lines.append("")

    call_args: List[str] = []
    post_call_lines: List[str] = []
    for idx, arg in enumerate(ctor_func.args):
        c_var = f"arg_{arg.name}"
        # Use sni_tb_js2c_parent() for SNI_H_LV_OBJ parent args so that
        # both regular LVGL objects and Activity Views (SNI_H_EOS_VIEW)
        # are accepted.  Null/undefined parent is rejected.
        use_parent_helper = arg.argument_mode == "parent_handle"
        if use_parent_helper:
            lines.append(f"    {fmt_var_decl(arg.c_type, c_var)};")
            lines.append(f"    if (!sni_tb_js2c_parent(args_p[{idx}], (void**)&{c_var}))")
            lines.append("    {")
            lines.append('        return sni_api_throw_error("Parent argument is required");')
            lines.append("    }")
            call_args.append(c_var)
            render_result = ArgRenderResult(call_expr=c_var, post_lines=[])
        else:
            render_result = render_arg_conversion(lines, f"args_p[{idx}]", arg, c_var, allow_null=True)
            call_args.append(render_result.call_expr)
            post_call_lines.extend(render_result.post_lines)
        lines.append("")

    call_text = ", ".join(call_args)
    if ctor_func.return_bridge.sni_type is None or ctor_func.return_bridge.c2js_mode != "bridge":
        raise RuntimeError(f"Resolved constructor {ctor_func.name} does not return an SNI object handle/value")

    native_call_name = ctor_func.native_call_name or ctor_func.name
    lines.append(f"    {fmt_var_decl(ctor_func.return_type, 'native_obj')} = {native_call_name}({call_text});" if call_text else f"    {fmt_var_decl(ctor_func.return_type, 'native_obj')} = {native_call_name}();")
    if post_call_lines:
        lines.extend(post_call_lines)
    lines.append(f"    if (!sni_tb_c2js_set_object(&native_obj, {ctor_func.return_bridge.sni_type}, call_info_p->this_value))")
    lines.append("    {")
    lines.append('        return sni_api_throw_error("Failed to bind native object");')
    lines.append("    }")
    lines.append("    return jerry_undefined();")
    lines.append("}")
    return "\n".join(lines)


def render_output_string_method_wrapper(cls: ApiClass, func: ApiFunction) -> str:
    if not func.args or func.output_string is None:
        raise RuntimeError(f"Resolved output-string method {func.name} is missing metadata")

    buffer_name, size_name, _ = func.output_string
    arg_by_name = {arg.name: (index, arg) for index, arg in enumerate(func.args)}
    if buffer_name not in arg_by_name or size_name not in arg_by_name:
        raise RuntimeError(f"Resolved output-string metadata for {func.name} references an unknown argument")

    buffer_index, _ = arg_by_name[buffer_name]
    size_index, _ = arg_by_name[size_name]
    js_buffer_index = buffer_index - 1
    js_size_index = size_index - 1
    if buffer_index == 0 or size_index == 0 or js_buffer_index < 0 or js_size_index < 0:
        raise RuntimeError(f"Resolved output-string metadata for {func.name} cannot target the receiver parameter")

    wrapper_name = f"sni_api_{func.name}"
    lines: List[str] = []
    render_function_docstring(lines, func, skip_this=True)
    func_prefix = f"jerry_value_t {wrapper_name}("
    func_indent = " " * len(func_prefix)
    lines.append(f"{func_prefix}const jerry_call_info_t *call_info_p,")
    lines.append(f"{func_indent}const jerry_value_t args_p[],")
    lines.append(f"{func_indent}const jerry_length_t args_count)")
    lines.append("{")
    lines.append(f"    if (args_count != {len(func.args) - 1})")
    lines.append("    {")
    lines.append('        return sni_api_throw_error("Invalid argument count");')
    lines.append("    }")
    lines.append("")

    this_arg = func.args[0]
    self_render = render_arg_conversion(lines, "call_info_p->this_value", this_arg, "self_obj")
    lines.append("")
    lines.append(f"    if (!jerry_value_is_string(args_p[{js_buffer_index}]))")
    lines.append("    {")
    lines.append('        return sni_api_throw_error("Invalid argument type");')
    lines.append("    }")
    lines.append(f"    if (!jerry_value_is_number(args_p[{js_size_index}]))")
    lines.append("    {")
    lines.append('        return sni_api_throw_error("Invalid argument type");')
    lines.append("    }")
    lines.append("    uint32_t output_size;")
    lines.append(f"    output_size = sni_tb_js2c_uint32(args_p[{js_size_index}]);")
    lines.append("    if (output_size == 0U)")
    lines.append("        return jerry_string_sz(\"\");")
    lines.append("    char *output_buf = eos_malloc(output_size);")
    lines.append("    if (!output_buf)")
    lines.append("        return sni_api_throw_error(\"Out of memory\");")
    lines.append("")
    native_call_name = func.native_call_name or func.name
    lines.append(f"    {native_call_name}({self_render.call_expr}, output_buf, output_size);")
    lines.append("    jerry_value_t result = jerry_string_sz(output_buf);")
    lines.append("    eos_free(output_buf);")
    lines.append("    return result;")
    lines.append("}")
    return "\n".join(lines)


def render_method_wrapper(cls: ApiClass, func: ApiFunction) -> str:
    if func.output_string is not None:
        return render_output_string_method_wrapper(cls, func)

    wrapper_name = f"sni_api_{func.name}"
    lines: List[str] = []
    render_function_docstring(lines, func, skip_this=True)

    if not func.args:
        raise RuntimeError(f"Resolved instance method {func.name} is missing its receiver parameter")

    this_arg = func.args[0]
    js_arg_count = len(func.args) - 1

    func_prefix = f"jerry_value_t {wrapper_name}("
    func_indent = " " * len(func_prefix)
    lines.append(f"{func_prefix}const jerry_call_info_t *call_info_p,")
    lines.append(f"{func_indent}const jerry_value_t args_p[],")
    lines.append(f"{func_indent}const jerry_length_t args_count)")
    lines.append("{")
    lines.append(f"    if (args_count != {js_arg_count})")
    lines.append("    {")
    lines.append('        return sni_api_throw_error("Invalid argument count");')
    lines.append("    }")
    lines.append("")

    self_render = render_arg_conversion(lines, "call_info_p->this_value", this_arg, "self_obj")
    lines.append("")

    call_args: List[str] = [self_render.call_expr]
    post_call_lines: List[str] = []
    for idx, arg in enumerate(func.args[1:]):
        c_var = f"arg_{arg.name}"
        output_only_value_arg = arg.argument_mode == "value_pointer_output"
        render_result = render_arg_conversion(lines, f"args_p[{idx}]", arg, c_var, output_only_value_arg=output_only_value_arg)
        call_args.append(render_result.call_expr)
        post_call_lines.extend(render_result.post_lines)
        lines.append("")

    call_text = ", ".join(call_args)
    native_call_name = func.native_call_name or func.name
    if func.return_bridge.c2js_mode == "void":
        lines.append(f"    {native_call_name}({call_text});")
        args_by_name = {arg.name: arg for arg in func.args}
        for name in func.cleanup_parameters:
            arg = args_by_name[name]
            lines.append(f"    sni_tb_remove_sub_resource_current(arg_{name}, {arg.bridge.sni_type});")
        if post_call_lines:
            lines.extend(post_call_lines)
        lines.append("    return jerry_undefined();")
        lines.append("}")
        return "\n".join(lines)

    lines.append(f"    {fmt_var_decl(func.return_type, 'result')} = {native_call_name}({call_text});")
    if func.result_owner == "this":
        lines.append(f"    sni_tb_link_sub_resource(self_obj, result, {func.return_bridge.sni_type});")
    if post_call_lines:
        lines.extend(post_call_lines)
    render_return_conversion(lines, func, "result")
    lines.append("}")
    return "\n".join(lines)


def render_static_wrapper(func: ApiFunction) -> str:
    if func.output_string is not None:
        raise RuntimeError(f"Resolved output-string override is incompatible with static API {func.name}")

    wrapper_name = f"sni_api_{func.name}"
    lines: List[str] = []
    render_function_docstring(lines, func)

    func_prefix = f"jerry_value_t {wrapper_name}("
    func_indent = " " * len(func_prefix)
    lines.append(f"{func_prefix}const jerry_call_info_t *call_info_p,")
    lines.append(f"{func_indent}const jerry_value_t args_p[],")
    lines.append(f"{func_indent}const jerry_length_t args_count)")
    lines.append("{")
    lines.append("    (void)call_info_p;")
    lines.append("")
    lines.append(f"    if (args_count != {len(func.args)})")
    lines.append("    {")
    lines.append('        return sni_api_throw_error("Invalid argument count");')
    lines.append("    }")
    lines.append("")

    call_args: List[str] = []
    post_call_lines: List[str] = []
    for idx, arg in enumerate(func.args):
        c_var = f"arg_{arg.name}"
        output_only_value_arg = arg.argument_mode == "value_pointer_output"
        render_result = render_arg_conversion(lines, f"args_p[{idx}]", arg, c_var, output_only_value_arg=output_only_value_arg)
        call_args.append(render_result.call_expr)
        post_call_lines.extend(render_result.post_lines)
        lines.append("")

    call_text = ", ".join(call_args)
    native_call_name = func.native_call_name or func.name
    if func.return_bridge.c2js_mode == "void":
        lines.append(f"    {native_call_name}({call_text});" if call_text else f"    {native_call_name}();")
        if post_call_lines:
            lines.extend(post_call_lines)
        lines.append("    return jerry_undefined();")
        lines.append("}")
        return "\n".join(lines)

    lines.append(f"    {fmt_var_decl(func.return_type, 'result')} = {native_call_name}({call_text});" if call_text else f"    {fmt_var_decl(func.return_type, 'result')} = {native_call_name}();")
    if func.result_owner:
        parent_index = next((index for index, arg in enumerate(func.args) if arg.name == func.result_owner), None)
        if parent_index is None:
            raise RuntimeError(f"Resolved resource owner {func.result_owner} is missing from {func.name}")
        lines.append(f"    sni_tb_link_sub_resource({call_args[parent_index]}, result, {func.return_bridge.sni_type});")
    if post_call_lines:
        lines.extend(post_call_lines)
    render_return_conversion(lines, func, "result")
    lines.append("}")
    return "\n".join(lines)


def render_property_getter_wrapper(cls: ApiClass, prop: ApiProperty, func: ApiFunction) -> str:
    wrapper_name = f"sni_api_prop_get_{sanitize_ident(cls.name)}_{sanitize_ident(prop.name)}"
    lines: List[str] = []
    render_function_docstring(lines, func, skip_this=True)

    if len(func.args) != 1:
        raise RuntimeError(f"Resolved property getter {func.name} must have only a receiver parameter")

    this_arg = func.args[0]

    func_prefix = f"jerry_value_t {wrapper_name}("
    func_indent = " " * len(func_prefix)
    lines.append(f"{func_prefix}const jerry_call_info_t *call_info_p,")
    lines.append(f"{func_indent}const jerry_value_t args_p[],")
    lines.append(f"{func_indent}const jerry_length_t args_count)")
    lines.append("{")
    lines.append("    (void)args_p;")
    lines.append("    if (args_count != 0)")
    lines.append("    {")
    lines.append('        return sni_api_throw_error("Invalid argument count");')
    lines.append("    }")
    lines.append("")

    self_render = render_arg_conversion(lines, "call_info_p->this_value", this_arg, "self_obj")
    lines.append("")

    if func.return_bridge.c2js_mode == "void":
        raise RuntimeError(f"Resolved property getter {func.name} cannot return void")

    native_call_name = func.native_call_name or func.name
    lines.append(f"    {fmt_var_decl(func.return_type, 'result')} = {native_call_name}({self_render.call_expr});")
    render_return_conversion(lines, func, "result")
    lines.append("}")
    return "\n".join(lines)


def render_property_setter_wrapper(cls: ApiClass, prop: ApiProperty, func: ApiFunction) -> str:
    wrapper_name = f"sni_api_prop_set_{sanitize_ident(cls.name)}_{sanitize_ident(prop.name)}"
    lines: List[str] = []
    render_function_docstring(lines, func, skip_this=True)

    if len(func.args) != 2:
        raise RuntimeError(f"Resolved property setter {func.name} must have receiver and value parameters")

    this_arg = func.args[0]
    value_arg = func.args[1]

    func_prefix = f"jerry_value_t {wrapper_name}("
    func_indent = " " * len(func_prefix)
    lines.append(f"{func_prefix}const jerry_call_info_t *call_info_p,")
    lines.append(f"{func_indent}const jerry_value_t args_p[],")
    lines.append(f"{func_indent}const jerry_length_t args_count)")
    lines.append("{")
    lines.append("    if (args_count != 1)")
    lines.append("    {")
    lines.append('        return sni_api_throw_error("Invalid argument count");')
    lines.append("    }")
    lines.append("")

    self_render = render_arg_conversion(lines, "call_info_p->this_value", this_arg, "self_obj")
    lines.append("")
    value_render = render_arg_conversion(lines, "args_p[0]", value_arg, "prop_value")
    lines.append("")
    native_call_name = func.native_call_name or func.name
    native_call_name = func.native_call_name or func.name
    lines.append(f"    {native_call_name}({self_render.call_expr}, {value_render.call_expr});")
    if value_render.post_lines:
        lines.extend(value_render.post_lines)
    lines.append("    return jerry_undefined();")
    lines.append("}")
    return "\n".join(lines)


def render_method_array(name: str, items: List[Tuple[str, str]]) -> str:
    lines = [f"const sni_method_desc_t {name}[] = {{"]
    for js_name, handler in items:
        lines.append(f"    {{.name = \"{js_name}\", .handler = {handler}}},")
    lines.append("    {.name = NULL, .handler = NULL},")
    lines.append("};")
    return "\n".join(lines)


def render_property_array(name: str, items: List[Tuple[str, Optional[str], Optional[str]]]) -> str:
    lines = [f"const sni_property_desc_t {name}[] = {{"]
    for js_name, getter, setter in items:
        getter_expr = getter if getter else "NULL"
        setter_expr = setter if setter else "NULL"
        lines.append(f"    {{.name = \"{js_name}\", .getter = {getter_expr}, .setter = {setter_expr}}},")
    lines.append("    {.name = NULL, .getter = NULL, .setter = NULL},")
    lines.append("};")
    return "\n".join(lines)


def _c_string_literal(value: str) -> str:
    """Encode arbitrary metadata as a portable C string literal."""
    escaped: List[str] = ['"']
    for byte in value.encode("utf-8"):
        if 0x20 <= byte <= 0x7E and byte not in {ord('"'), ord("\\")}:
            escaped.append(chr(byte))
        elif byte == ord('"'):
            escaped.append('\\"')
        elif byte == ord("\\"):
            escaped.append("\\\\")
        elif byte == 0x0A:
            escaped.append("\\n")
        elif byte == 0x0D:
            escaped.append("\\r")
        elif byte == 0x09:
            escaped.append("\\t")
        else:
            escaped.append(f"\\{byte:03o}")
    escaped.append('"')
    return "".join(escaped)


def _render_constant_value(item: ApiConstantIR) -> str:
    if item.value_kind == "int" and item.c_expression:
        return f"{{.name = {_c_string_literal(item.name)}, .type = SNI_CONST_INT, .value.i = {item.c_expression}}},"
    if item.value_kind == "float" and item.c_expression:
        return f"{{.name = {_c_string_literal(item.name)}, .type = SNI_CONST_FLOAT, .value.f = {item.c_expression}}},"
    if item.value_kind == "string" and item.c_expression:
        return f"{{.name = {_c_string_literal(item.name)}, .type = SNI_CONST_STRING, .value.s = {item.c_expression}}},"
    return f"{{.name = {_c_string_literal(item.name)}, .type = SNI_CONST_UNDEFINED, .value.i = 0}},"


def render_constant_array(name: str, items: List[ApiConstantIR]) -> str:
    lines = [f"const sni_constant_desc_t {name}[] = {{"]
    for item in items:
        value = _render_constant_value(item)
        if item.availability_guard and item.value_kind is not None:
            if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", item.availability_guard):
                raise RuntimeError(f"Invalid constant availability guard for {item.name}: {item.availability_guard!r}")
            lines.append(f"#if defined({item.availability_guard})")
            lines.append(f"    {value}")
            lines.append("#else")
            lines.append(
                f"    {{.name = {_c_string_literal(item.name)}, .type = SNI_CONST_UNDEFINED, .value.i = 0}},"
            )
            lines.append("#endif")
        else:
            lines.append(f"    {value}")
    lines.append("    {.name = NULL, .type = SNI_CONST_INT, .value.i = 0},")
    lines.append("};")
    return "\n".join(lines)


def render_macro_catalog(name: str, macros: List[ApiMacroIR]) -> str:
    lines = [f"const sni_macro_desc_t {name}[] = {{"]
    for macro in macros:
        if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", macro.name):
            raise RuntimeError(f"Invalid LVGL macro identifier: {macro.name!r}")
        function_like = macro.parameters is not None
        parameters_json = None if macro.parameters is None else json.dumps(list(macro.parameters), ensure_ascii=False, separators=(",", ":"))
        params_c = "NULL" if parameters_json is None else _c_string_literal(parameters_json)
        initializer_c = "NULL" if macro.initializer is None else _c_string_literal(macro.initializer)
        value_kind = macro.value_kind
        if value_kind == "int":
            value_type = "SNI_CONST_INT"
            value_field = f".value.i = {macro.name}"
        elif value_kind == "float":
            value_type = "SNI_CONST_FLOAT"
            value_field = f".value.f = {macro.name}"
        elif value_kind == "string":
            value_type = "SNI_CONST_STRING"
            value_field = f".value.s = {macro.name}"
        else:
            value_type = "SNI_CONST_UNDEFINED"
            value_field = ".value.i = 0"
        common = (
            f".name = {_c_string_literal(macro.name)}, .function_like = {str(function_like).lower()}, "
            f".parameters_json = {params_c}, .initializer = {initializer_c}"
        )
        lines.append(f"#if defined({macro.name})")
        lines.append(
            f"    {{{common}, .defined = true, .value_available = {str(value_kind is not None).lower()}, "
            f".value_type = {value_type}, {value_field}}},"
        )
        lines.append("#else")
        lines.append(
            f"    {{{common}, .defined = false, .value_available = false, "
            ".value_type = SNI_CONST_UNDEFINED, .value.i = 0},"
        )
        lines.append("#endif")
    lines.append("    {.name = NULL},")
    lines.append("};")
    return "\n".join(lines)


def render_class_block(
    classes: List[ApiClassIR],
    constructor_wrapper_names: Dict[str, str],
    method_array_names: Dict[str, str],
    property_array_names: Dict[str, str],
    static_method_array_names: Dict[str, str],
    constant_array_names: Dict[str, str],
    root_constant_array_name: str,
) -> str:
    lines: List[str] = []

    for cls in classes:
        class_var = f"lv_class_desc_{sanitize_ident(cls.name)}"
        base_expr = "NULL"
        if cls.base:
            base_expr = f"&lv_class_desc_{sanitize_ident(cls.base)}"

        lines.append(f"const sni_class_desc_t {class_var} = {{")
        lines.append(f"    .name = \"{cls.name}\",")
        is_static = not cls.has_constructor
        lines.append(f"    .constructor = {constructor_wrapper_names[cls.name]},")
        lines.append(f"    .base_class = {'NULL' if is_static else base_expr},")
        methods_expr = "NULL" if is_static else method_array_names[cls.name]
        properties_expr = "NULL" if is_static else property_array_names[cls.name]
        lines.append(f"    .methods = {methods_expr},")
        lines.append(f"    .properties = {properties_expr},")
        lines.append(f"    .static_methods = {static_method_array_names[cls.name]},")
        lines.append(f"    .constants = {constant_array_names[cls.name]},")
        lines.append("};")
        lines.append("")

    lines.append("const sni_class_desc_t *const lv_api_classes[] = {")
    for cls in classes:
        lines.append(f"    &lv_class_desc_{sanitize_ident(cls.name)},")
    lines.append("    NULL,")
    lines.append("};")

    init_mount = """
void sni_api_lv_init(void)
{
    sni_cb_runtime_init();
    lv_api_obj = sni_api_build(lv_api_classes);
    if (!jerry_value_is_object(lv_api_obj))
    {
        EOS_LOG_E("Failed to build LV API object");
    }
    if (!sni_api_register_constants(lv_root_constants, lv_api_obj))
    {
        EOS_LOG_E("Failed to register LV root constants");
    }
    if (!sni_api_register_macro_catalog(lv_macro_catalog, lv_api_obj))
    {
        EOS_LOG_E("Failed to register LV macro catalog");
    }
}

void sni_api_lv_mount(jerry_value_t realm)
{
    bool result = sni_api_mount(realm, lv_api_obj, LV_API_NAME);
    if (!result)
    {
        EOS_LOG_E("Failed to mount LVGL API");
    }
}
""".strip("\n")

    lines.append("")
    lines.append(init_mount)

    return "\n".join(lines)


def normalize_args(raw_args: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    cleaned: List[Dict[str, Any]] = []
    for item in raw_args:
        arg_type = normalize_c_type(item.get("type"))
        arg_name = item.get("name")
        if arg_type == "void" and (arg_name is None or str(arg_name).strip() == ""):
            continue
        cleaned.append(item)
    return cleaned


def entry_name(func_name: str) -> str:
    if not func_name.startswith("lv_"):
        return func_name
    rest = func_name[3:]
    parts = rest.split("_")
    if len(parts) <= 1:
        return rest
    remaining = "_".join(parts[1:])
    return snake_to_camel(remaining)


def _api_function_from_ir(record: ApiRecord, uses: List[ApiUse]) -> ApiFunction:
    if record.status != ApiStatus.ACCEPTED_GENERIC:
        raise RuntimeError(f"API renderer received non-generic API {record.name}: {record.status.value}")
    return_use = next((use for use in uses if use.position == "return"), None)
    if return_use is None:
        raise RuntimeError(f"Resolved API {record.name} has no return conversion")

    def bridge_for(use: ApiUse) -> TypeBridge:
        if use.status != ApiStatus.ACCEPTED_GENERIC:
            raise RuntimeError(
                f"Resolved generic API {record.name} contains unresolved {use.position}: {use.status.value}"
            )
        if use.position != "return" and use.sni_type is None:
            raise RuntimeError(f"Resolved generic API {record.name} has no SNI type for {use.position}")
        if use.position != "return" and use.js2c_mode not in {"macro", "string_fn", "bridge"}:
            raise RuntimeError(
                f"Resolved generic API {record.name} has invalid JS-to-C mode for {use.position}: {use.js2c_mode}"
            )
        if use.position == "return" and use.sni_type is None and use.c2js_mode != "void":
            raise RuntimeError(f"Resolved generic API {record.name} has an unresolved return conversion")
        if use.position == "return" and use.sni_type is not None and use.c2js_mode not in {"macro", "string", "bridge"}:
            raise RuntimeError(f"Resolved generic API {record.name} has invalid C-to-JS mode: {use.c2js_mode}")
        return TypeBridge(
            use.use_site.spelling,
            use.js_check,
            use.js2c_mode,
            use.js2c_expr,
            use.sni_type,
            use.c2js_mode,
            use.c2js_expr,
        )

    args: List[FuncArg] = []
    for use in uses:
        if use.position == "return":
            continue
        args.append(
            FuncArg(
                name=use.name or use.position,
                c_type=use.use_site.spelling,
                bridge=bridge_for(use),
                docstring=use.docstring,
                js_type=use.js_type,
                lifecycle_class=use.lifecycle_class,
                argument_mode=use.argument_mode,
                allow_null=use.allow_null,
                copy_back=use.copy_back,
                pointee_type=use.pointee_type,
            )
        )
    return ApiFunction(
        name=record.name,
        return_type=return_use.use_site.spelling,
        return_bridge=bridge_for(return_use),
        args=args,
        docstring=record.docstring,
        return_docstring=record.return_docstring,
        return_js_type=return_use.js_type,
        lifecycle_class=return_use.lifecycle_class,
        native_call_name=record.native_call_name,
        output_string=record.output_string,
        result_owner=record.result_owner,
        cleanup_parameters=list(record.cleanup_parameters),
    )


def _render_entries(
    ir: ResolvedApiSurface,
) -> Tuple[str, Dict[str, Any]]:
    wrappers: List[str] = []
    blocks: List[str] = []

    records = {record.name: record for record in ir.apis}
    uses_by_api: Dict[str, List[ApiUse]] = {}
    for use in ir.uses:
        uses_by_api.setdefault(use.function, []).append(use)
    functions: Dict[str, ApiFunction] = {}
    rendered_names: set[str] = set()

    def get_function(name: str) -> ApiFunction:
        if name not in functions:
            record = records.get(name)
            if record is None:
                raise RuntimeError(f"Resolved class surface references missing API {name}")
            functions[name] = _api_function_from_ir(record, uses_by_api.get(name, []))
        return functions[name]

    constructor_wrapper_names: Dict[str, str] = {}
    method_array_names: Dict[str, str] = {}
    property_array_names: Dict[str, str] = {}
    static_method_array_names: Dict[str, str] = {}
    constant_array_names: Dict[str, str] = {}

    for cls in ir.classes:
        cls_id = sanitize_ident(cls.name)

        ctor_name = cls.configured_constructor
        ctor_func = None
        if ctor_name is not None:
            if cls.constructor_binding is not None:
                constructor_wrapper_names[cls.name] = cls.constructor_binding
            else:
                ctor_func = get_function(ctor_name)
                ctor_wrapper = f"sni_api_ctor_{cls_id}"
                constructor_wrapper_names[cls.name] = ctor_wrapper
                wrappers.append(render_constructor_wrapper(cls, ctor_func))
            rendered_names.add(ctor_name)
        else:
            constructor_wrapper_names[cls.name] = "NULL"

        instance_items: List[Tuple[str, str]] = []
        for ref in cls.methods:
            if ref.special_binding is not None:
                instance_items.append((entry_name(ref.function), ref.special_binding))
            else:
                method_func = get_function(ref.function)
                wrappers.append(render_method_wrapper(cls, method_func))
                instance_items.append((entry_name(method_func.name), f"sni_api_{method_func.name}"))
            rendered_names.add(ref.function)

        existing_method_names = {name for name, _ in instance_items}
        for extra_js_name, extra_c_name in cls.extra_methods:
            if extra_js_name not in existing_method_names:
                instance_items.append((extra_js_name, extra_c_name))

        method_array_name = f"lv_class_methods_{cls_id}"
        method_array_names[cls.name] = method_array_name
        blocks.append(render_method_array(method_array_name, instance_items))

        static_items: List[Tuple[str, str]] = []
        for ref in cls.static_methods:
            if ref.special_binding is not None:
                static_items.append((entry_name(ref.function), ref.special_binding))
            else:
                static_func = get_function(ref.function)
                wrappers.append(render_static_wrapper(static_func))
                static_items.append((entry_name(static_func.name), f"sni_api_{static_func.name}"))
            rendered_names.add(ref.function)

        static_array_name = f"lv_class_static_methods_{cls_id}"
        static_method_array_names[cls.name] = static_array_name
        blocks.append(render_method_array(static_array_name, static_items))

        prop_items: List[Tuple[str, Optional[str], Optional[str]]] = []
        for prop in cls.properties:
            getter_name = None
            setter_name = None

            if prop.getter:
                if prop.getter.special_binding is not None:
                    getter_name = prop.getter.special_binding
                else:
                    getter_func = get_function(prop.getter.function)
                    wrappers.append(render_property_getter_wrapper(cls, ApiProperty(prop.name, prop.getter.function, None), getter_func))
                    getter_name = f"sni_api_prop_get_{cls_id}_{sanitize_ident(prop.name)}"
                rendered_names.add(prop.getter.function)

            if prop.setter:
                if prop.setter.special_binding is not None:
                    setter_name = prop.setter.special_binding
                else:
                    setter_func = get_function(prop.setter.function)
                    wrappers.append(render_property_setter_wrapper(cls, ApiProperty(prop.name, None, prop.setter.function), setter_func))
                    setter_name = f"sni_api_prop_set_{cls_id}_{sanitize_ident(prop.name)}"
                rendered_names.add(prop.setter.function)

            prop_items.append((snake_to_camel(prop.name), getter_name, setter_name))

        existing_prop_names = {name for name, _, _ in prop_items}
        for extra_name, extra_getter, extra_setter in cls.extra_properties:
            if extra_name not in existing_prop_names:
                prop_items.append((extra_name, extra_getter, extra_setter))

        prop_array_name = f"lv_class_properties_{cls_id}"
        property_array_names[cls.name] = prop_array_name
        blocks.append(render_property_array(prop_array_name, prop_items))

        const_array_name = f"lv_class_constants_{cls_id}"
        constant_array_names[cls.name] = const_array_name
        blocks.append(render_constant_array(const_array_name, cls.constants))

    root_constant_array_name = "lv_root_constants"
    blocks.append(render_constant_array(root_constant_array_name, ir.root_constants))

    macro_catalog_array_name = "lv_macro_catalog"
    blocks.append(render_macro_catalog(macro_catalog_array_name, ir.macros))

    blocks.append(
        render_class_block(
            ir.classes,
            constructor_wrapper_names,
            method_array_names,
            property_array_names,
            static_method_array_names,
            constant_array_names,
            root_constant_array_name,
        )
    )

    encountered_types = sorted(
        {
            use.sni_type
            for name in rendered_names
            for use in uses_by_api.get(name, [])
            if use.sni_type and (use.sni_type.startswith("SNI_H_") or use.sni_type.startswith("SNI_V_"))
        }
    )
    return "\n\n".join(wrappers + blocks), {
        "api_names": sorted(rendered_names),
        "sni_types": encountered_types,
        "class_count": len(ir.classes),
        "constructor_count": sum(item.configured_constructor is not None for item in ir.classes),
        "method_count": sum(len(item.methods) for item in ir.classes),
        "static_method_count": sum(len(item.static_methods) for item in ir.classes),
        "property_count": sum(len(item.properties) for item in ir.classes),
        "global_constant_count": len(ir.root_constants),
        "macro_count": len(ir.macros),
        "diagnostics": [],
    }


def render_api(surface: ResolvedApiSurface, lvgl_version: Tuple[int, int, int]) -> Tuple[str, Dict[str, Any]]:
    """Render only the accepted, fully resolved API surface to C."""
    if not isinstance(surface, ResolvedApiSurface):
        raise TypeError("API renderer requires the accepted-only ResolvedApiSurface")
    records = {record.name: record for record in surface.apis}
    required_names: set[str] = set()
    for cls in surface.classes:
        if cls.configured_constructor:
            required_names.add(cls.configured_constructor)
        required_names.update(ref.function for ref in cls.methods)
        required_names.update(ref.function for ref in cls.static_methods)
        required_names.update(
            ref.function
            for prop in cls.properties
            for ref in (prop.getter, prop.setter)
            if ref is not None
        )
    missing = sorted(required_names - records.keys())
    if missing:
        raise RuntimeError(f"Resolved class surface references missing API results: {missing[:12]}")
    for name in sorted(required_names):
        record = records[name]
        if record.status not in {ApiStatus.ACCEPTED_GENERIC, ApiStatus.ACCEPTED_SPECIAL}:
            raise RuntimeError(f"API renderer received rejected binding {name}: {record.status.value}")
    for cls in surface.classes:
        if cls.constructor_binding and cls.configured_constructor:
            if records[cls.configured_constructor].status != ApiStatus.ACCEPTED_SPECIAL:
                raise RuntimeError(f"Special constructor {cls.configured_constructor} is not resolved as accepted special")
        for ref in cls.methods + cls.static_methods:
            if records[ref.function].status == ApiStatus.ACCEPTED_SPECIAL and not ref.special_binding:
                raise RuntimeError(f"Special API {ref.function} has no resolved wrapper symbol")
        for prop in cls.properties:
            for ref in (prop.getter, prop.setter):
                if ref and records[ref.function].status == ApiStatus.ACCEPTED_SPECIAL and not ref.special_binding:
                    raise RuntimeError(f"Special property API {ref.function} has no resolved wrapper symbol")

    table_text, result = _render_entries(surface)
    if set(result["api_names"]) != set(surface.names):
        missing = sorted(set(surface.names) - set(result["api_names"]))
        extra = sorted(set(result["api_names"]) - set(surface.names))
        raise RuntimeError(f"Resolved API surface render mismatch; missing={missing[:12]}, extra={extra[:12]}")
    generated = HEADER_TEXT + "\n" + render_lvgl_compatibility_guard(lvgl_version, surface.event_assertions) + "\n" + table_text + "\n"
    generated += "\n/* SNI_API_SURFACE_BEGIN\n"
    generated += "\n".join(sorted(set(surface.names)))
    generated += "\nSNI_API_SURFACE_END */\n"
    return generated, result
