"""Render value-object descriptors from the resolved in-memory type IR."""

from __future__ import annotations

from typing import Any

from ..core.ir import BindingIR, Representation
from ..core.lvgl_model import LVGLModel
from ..core.resolver import PRIMITIVE_SNI


def _sni_field_type(type_name: str, ir: BindingIR, model: LVGLModel) -> str:
    info = ir.types.get(type_name)
    if info is None:
        canonical, category, _ = model.resolve_declaration(type_name)
        if canonical in PRIMITIVE_SNI:
            return PRIMITIVE_SNI[canonical]
        if category.value == "enum":
            return "SNI_T_INT32"
        raise ValueError(f"unresolved value-object field type {type_name}")
    if info.representation == Representation.PRIMITIVE:
        return PRIMITIVE_SNI[info.canonical_name]
    if info.representation == Representation.ENUM:
        return "SNI_T_INT32"
    if info.representation == Representation.VALUE_OBJECT:
        base = info.canonical_name[:-2] if info.canonical_name.endswith("_t") else info.canonical_name
        return "SNI_V_" + base.upper()
    raise ValueError(f"value-object field {type_name} resolves to {info.representation.value}")


def render_lv_types(ir: BindingIR, model: LVGLModel) -> str:
    value_types = sorted(
        {
            info.canonical_name
            for info in ir.types.values()
            if info.representation == Representation.VALUE_OBJECT and info.canonical_name in model.structures
        }
    )
    lines = [
        "/**",
        " * @file sni_lv_types.c",
        " * @brief LVGL Value Object field tables.",
        " *",
        " * This file is generated by generate_sni.py. Do not edit manually.",
        " */",
        "",
        '#include "sni_lv_types.h"',
        "",
        "/* Includes ---------------------------------------------------*/",
        "#include <stddef.h>",
        '#include "lvgl.h"',
        '#include "sni_type_bridge.h"',
        '#include "sni_types.h"',
        "",
        "/* Value Object property tables */",
        "",
    ]
    registrations: list[tuple[str, str]] = []
    for type_name in value_types:
        fields = model.field_facts(type_name)
        if not fields:
            raise ValueError(f"inferred Value Object {type_name} has no fields")
        base = type_name[:-2] if type_name.endswith("_t") else type_name
        table = f"{base}_props"
        desc = f"{base}_prop"
        lines.append(f"static const sni_val_prop_t {table}[] = {{")
        bitfield_storage_offset = None
        for index, field in enumerate(fields):
            if field.bitsize is not None:
                if index == 0:
                    bitfield_storage_offset = "0"
                else:
                    for previous in reversed(fields[:index]):
                        if previous.bitsize is None:
                            bitfield_storage_offset = f"offsetof({type_name}, {previous.name})"
                            break
                    if bitfield_storage_offset is None:
                        bitfield_storage_offset = "0"
                break
        for field in fields:
            sni_type = _sni_field_type(field.type_name, ir, model)
            offset = bitfield_storage_offset if field.bitsize is not None else f"offsetof({type_name}, {field.name})"
            width = int(field.bitsize) if field.bitsize is not None else 0
            lines.extend(
                [
                    "    {",
                    f'        .name = "{field.name}",',
                    f"        .type = {sni_type},",
                    f"        .offset = {offset},",
                    f"        .bit_width = {width},",
                    "    },",
                ]
            )
        lines.extend(
            [
                "};",
                "",
                f"static const sni_val_obj_t {desc} = {{",
                f"    .type = SNI_V_{base.upper()},",
                f"    .prop_count = {len(fields)},",
                f"    .props = {table},",
                "};",
                "",
            ]
        )
        registrations.append((type_name, desc))

    lines.append("/* Value Object registry */")
    lines.append("")
    lines.append("static const sni_val_obj_t *const sni_lv_types[] = {")
    for _, descriptor in registrations:
        lines.append(f"    &{descriptor},")
    lines.extend(
        [
            "};",
            "",
            "void sni_lv_types_init(void)",
            "{",
            "    for (size_t i = 0; i < sizeof(sni_lv_types) / sizeof(sni_lv_types[0]); i++)",
            "    {",
            "        sni_tb_register_val_obj(sni_lv_types[i]);",
            "    }",
            "}",
            "",
        ]
    )
    return "\n".join(lines)
