/**
 * @file sni_lv_types.c
 * @brief LVGL Value Object field tables.
 *
 * This file is generated by generate_sni.py. Do not edit manually.
 */

#include "sni_lv_types.h"

/* Includes ---------------------------------------------------*/
#include <stddef.h>
#include "lvgl.h"
#include "sni_type_bridge.h"
#include "sni_types.h"

/* Value Object property tables */

static const sni_val_prop_t lv_area_props[] = {
    {
        .name = "x1",
        .type = SNI_T_INT32,
        .offset = offsetof(lv_area_t, x1),
        .bit_width = 0,
    },
    {
        .name = "y1",
        .type = SNI_T_INT32,
        .offset = offsetof(lv_area_t, y1),
        .bit_width = 0,
    },
    {
        .name = "x2",
        .type = SNI_T_INT32,
        .offset = offsetof(lv_area_t, x2),
        .bit_width = 0,
    },
    {
        .name = "y2",
        .type = SNI_T_INT32,
        .offset = offsetof(lv_area_t, y2),
        .bit_width = 0,
    },
};

static const sni_val_obj_t lv_area_prop = {
    .type = SNI_V_LV_AREA,
    .prop_count = 4,
    .props = lv_area_props,
};

static const sni_val_prop_t lv_calendar_date_props[] = {
    {
        .name = "year",
        .type = SNI_T_UINT16,
        .offset = offsetof(lv_calendar_date_t, year),
        .bit_width = 0,
    },
    {
        .name = "month",
        .type = SNI_T_UINT8,
        .offset = offsetof(lv_calendar_date_t, month),
        .bit_width = 0,
    },
    {
        .name = "day",
        .type = SNI_T_UINT8,
        .offset = offsetof(lv_calendar_date_t, day),
        .bit_width = 0,
    },
};

static const sni_val_obj_t lv_calendar_date_prop = {
    .type = SNI_V_LV_CALENDAR_DATE,
    .prop_count = 3,
    .props = lv_calendar_date_props,
};

static const sni_val_prop_t lv_color32_props[] = {
    {
        .name = "blue",
        .type = SNI_T_UINT8,
        .offset = offsetof(lv_color32_t, blue),
        .bit_width = 0,
    },
    {
        .name = "green",
        .type = SNI_T_UINT8,
        .offset = offsetof(lv_color32_t, green),
        .bit_width = 0,
    },
    {
        .name = "red",
        .type = SNI_T_UINT8,
        .offset = offsetof(lv_color32_t, red),
        .bit_width = 0,
    },
    {
        .name = "alpha",
        .type = SNI_T_UINT8,
        .offset = offsetof(lv_color32_t, alpha),
        .bit_width = 0,
    },
};

static const sni_val_obj_t lv_color32_prop = {
    .type = SNI_V_LV_COLOR32,
    .prop_count = 4,
    .props = lv_color32_props,
};

static const sni_val_prop_t lv_color_props[] = {
    {
        .name = "blue",
        .type = SNI_T_UINT8,
        .offset = offsetof(lv_color_t, blue),
        .bit_width = 0,
    },
    {
        .name = "green",
        .type = SNI_T_UINT8,
        .offset = offsetof(lv_color_t, green),
        .bit_width = 0,
    },
    {
        .name = "red",
        .type = SNI_T_UINT8,
        .offset = offsetof(lv_color_t, red),
        .bit_width = 0,
    },
};

static const sni_val_obj_t lv_color_prop = {
    .type = SNI_V_LV_COLOR,
    .prop_count = 3,
    .props = lv_color_props,
};

static const sni_val_prop_t lv_grad_stop_props[] = {
    {
        .name = "color",
        .type = SNI_V_LV_COLOR,
        .offset = offsetof(lv_grad_stop_t, color),
        .bit_width = 0,
    },
    {
        .name = "opa",
        .type = SNI_T_UINT8,
        .offset = offsetof(lv_grad_stop_t, opa),
        .bit_width = 0,
    },
    {
        .name = "frac",
        .type = SNI_T_UINT8,
        .offset = offsetof(lv_grad_stop_t, frac),
        .bit_width = 0,
    },
};

static const sni_val_obj_t lv_grad_stop_prop = {
    .type = SNI_V_LV_GRAD_STOP,
    .prop_count = 3,
    .props = lv_grad_stop_props,
};

static const sni_val_prop_t lv_point_props[] = {
    {
        .name = "x",
        .type = SNI_T_INT32,
        .offset = offsetof(lv_point_t, x),
        .bit_width = 0,
    },
    {
        .name = "y",
        .type = SNI_T_INT32,
        .offset = offsetof(lv_point_t, y),
        .bit_width = 0,
    },
};

static const sni_val_obj_t lv_point_prop = {
    .type = SNI_V_LV_POINT,
    .prop_count = 2,
    .props = lv_point_props,
};

/* Value Object registry */

static const sni_val_obj_t *const sni_lv_types[] = {
    &lv_area_prop,
    &lv_calendar_date_prop,
    &lv_color32_prop,
    &lv_color_prop,
    &lv_grad_stop_prop,
    &lv_point_prop,
};

void sni_lv_types_init(void)
{
    for (size_t i = 0; i < sizeof(sni_lv_types) / sizeof(sni_lv_types[0]); i++)
    {
        sni_tb_register_val_obj(sni_lv_types[i]);
    }
}
